ProyectoIntegrador2018/tutor_virtual

TutorVirtual/app/Http/Controllers/HomeController.php, TutorVirtual/public/css/test.scss, TutorVirtual/resources/views/auth/login.blade.php, TutorVirtual/resources/views/auth/passwords/email.blade.php, TutorVirtual/resources/views/auth/passwords/reset.blade.php, TutorVirtual/resources/views/auth/register.blade.php, TutorVirtual/resources/views/auth/verify.blade.php, TutorVirtual/resources/views/home.blade.php, TutorVirtual/resources/views/layouts/app.blade.php, TutorVirtual/resources/views/welcome.blade.php, TutorVirtual/routes/web.php
A Login.php and Register.php have been created, you still need to create the database and run xampp to make this work
=> Created login and register using php

TutorVirtual/public/css/stylesheet.css, TutorVirtual/resources/views/menuLateral.blade.php, TutorVirtual/routes/web.php
Primer parte del menu lateral, solo se creó la estructura y CSS, los elementos no hacen nada al hacer click. Se le dio la ruta de /menuLateral
=> Menu Lateral pt1

TutorVirtual/public/css/stylesheet.css, TutorVirtual/resources/js/components/MainComponent.js, TutorVirtual/resources/views/menuLateral.blade.php
Segunda parte del menu agregada. No hay nada funcional.
=> MenuLateralpt2

app/Http/Controllers/Api/CursoController.php, public/js/app.js, resources/js/components/Content/Cursos/Listing.js, routes/web.php
=> Added delete funcionality

app/Http/Controllers/Api/CursoController.php, public/js/app.js, resources/js/components/Content/Cursos/Listing.js, routes/web.php
=> Mostrar detalle de curso

Procfile
=> Procfile for heroku

.env.example
=> udpate env

app/Alumno.php, app/Http/Controllers/Api/AlumnoController.php, app/Http/Controllers/Api/CursoController.php, app/Providers/AppServiceProvider.php, database/migrations/2018_10_10_224557_create_alumnos.php, public/js/app.js, resources/js/components/Content/Alumnos/Alumnos.js, resources/js/components/Content/Alumnos/Alumnos_New.js, resources/js/components/Content/Cursos/Listing.js, resources/js/components/MainComponent.js, resources/js/components/SubNavbars/Alumnos_Sub.js, routes/web.php
Add Alumno controller,Model,add,delente and Get operations
=> Add Alumno controller,Model,add,delente and Get operations

app/Http/Controllers/Api/AlumnoController.php, public/js/app.js, resources/js/components/Content/Alumnos/Alumnos.js, resources/js/components/Content/Cursos/Listing.js, routes/web.php
=> put de alumnos

app/Http/Controllers/Api/AlumnoController.php, public/js/app.js, resources/js/components/Content/Alumnos/Alumnos.js, resources/js/components/SubNavbars/Alumnos_Sub.js, routes/web.php
=> Added search to alumno

app/Http/Controllers/Api/AlumnoController.php, app/Http/Controllers/Api/CursoController.php, package-lock.json, package.json, public/js/app.js, resources/js/components/Content/Alumnos/Alumnos_New.js, resources/js/components/Content/Cursos/Listing.js, resources/js/components/Content/Cursos/New.js, routes/web.php
add search curso, alertas al agregar y eliminar cursos y alumnos
=> add search curso, alertas al agregar y eliminar cursos y alumnos

package-lock.json, public/js/app.js, resources/js/components/Content/Alumnos/Alumnos.js
=> add popup delete to alumnos

app/Http/Controllers/Api/CursoController.php, package-lock.json, package.json, public/js/app.js, resources/js/components/Content/Alumnos/Alumnos.js, resources/js/components/Content/Cursos/Listing.js, resources/js/components/Content/Tutores/Tutores.js
Se agrego Fecha inicio a los cursos y un modal a cursos, alumnos y tutores cada vez que se actualice algun detalle
=> CursosDisplay & ModalDeUpdate

app/Http/Controllers/Api/AlumnoController.php, app/Http/Controllers/Api/TutorController.php, database/migrations/2018_10_10_224557_create_alumnos.php, database/migrations/2018_11_02_232417_create_tutores.php, public/js/app.js, resources/js/components/Content/Alumnos/Alumnos.js, resources/js/components/Content/Alumnos/Alumnos_New.js, resources/js/components/Content/Tutores/Tutores.js
-Se quitaron las doble p en apellido
-Cambiado "Delete" -> "Eliminar" en Tutores
-Cambiado "Hide Modal" -> "Regresar" en modal Tutores
-Corregida posición de botón agregar nuevo tutor
-Corregido despliegue de pais en lugar de curso en Tutores
-Eliminado pais de Alumno
=> Correcciones

app/Http/Controllers/Api/AlumnoController.php, database/migrations/2018_10_10_224557_create_alumnos.php, public/js/app.js, resources/js/components/Content/Alumnos/Alumnos.js, resources/js/components/Content/Alumnos/Alumnos_New.js
Added socio periodo etc to alumno
=> Added socio periodo etc to alumno

app/Grupo.php, app/Http/Controllers/Api/GrupoController.php, database/migrations/2018_11_11_014525_create_grupos.php, public/js/app.js, resources/js/components/Content/Grupos/Grupos.js, resources/js/components/Content/Grupos/Grupos_New.js, resources/js/components/MainComponent.js, resources/js/components/SubNavbars/Grupos_Sub.js, routes/web.php
=> added grupos

.circleci/config.yml, Makefile, README.md, bin/bump_version.sh, bin/docker_build.sh, bin/docker_check.sh, bin/docker_push.sh, bin/docker_rmi.sh, bin/docker_run.sh, docker-compose.yml, test/controllers/aliados_controller_test.rb, test/controllers/cursos_controller_test.rb, test/controllers/preinscritos_controller_test.rb, test/controllers/sessions_controller_test.rb, test/controllers/users_controller_test.rb, test/fixtures/users.yml, test/models/user_test.rb
Add #128  
- Add circleci config file
- Remove non-functional Test cases
- Add makefile for automation
- Add docker scripts for automation purposes
=> CI Integration

.circleci/config.yml, .gitignore, Makefile, app/views/layouts/application.html.erb, app/views/layouts/devise.html.erb, bin/docker_run_local_production.sh, bin/heroku_deploy.sh, bin/heroku_push.sh, bin/heroku_release.sh, config/environments/production.rb
- Enables the project in production
- Do #131
=> Sets Production environment

tutor-virtual-2/Gemfile, tutor-virtual-2/Gemfile.lock, tutor-virtual-2/app/assets/javascripts/application.js, tutor-virtual-2/app/assets/stylesheets/application.scss, tutor-virtual-2/app/assets/stylesheets/home.scss, tutor-virtual-2/app/assets/stylesheets/scaffolds.scss, tutor-virtual-2/app/assets/stylesheets/signin.css, tutor-virtual-2/app/views/devise/sessions/new.html.erb, tutor-virtual-2/app/views/home/index.html.erb, tutor-virtual-2/app/views/layouts/application.html.erb
*Added SideBar
*Added Home Page
*Fixed css SignIn
=> SideBar + FrontEnd Inicio

tutor-virtual-2/Gemfile, tutor-virtual-2/Gemfile.lock, tutor-virtual-2/app/assets/stylesheets/courses.scss, tutor-virtual-2/app/assets/stylesheets/scaffolds.scss, tutor-virtual-2/app/controllers/courses_controller.rb, tutor-virtual-2/app/models/course.rb, tutor-virtual-2/app/views/courses/_form.html.erb, tutor-virtual-2/app/views/courses/edit.html.erb, tutor-virtual-2/app/views/courses/index.html.erb, tutor-virtual-2/app/views/courses/new.html.erb, tutor-virtual-2/app/views/courses/show.html.erb, tutor-virtual-2/app/views/layouts/application.html.erb, tutor-virtual-2/config/routes.rb
Courses Back End
Most Front End
* Front and Back End Courses
=> Courses BackEnd

app/assets/javascripts/groups.coffee, app/assets/stylesheets/groups.scss, app/assets/stylesheets/scaffolds.scss, app/controllers/groups_controller.rb, app/helpers/groups_helper.rb, app/models/group.rb, app/views/groups/_form.html.erb, app/views/groups/_group.json.jbuilder, app/views/groups/edit.html.erb, app/views/groups/index.html.erb, app/views/groups/index.json.jbuilder, app/views/groups/new.html.erb, app/views/groups/show.html.erb, app/views/groups/show.json.jbuilder, config/routes.rb, db/migrate/20191117205958_create_groups.rb, db/schema.rb, test/controllers/groups_controller_test.rb, test/fixtures/groups.yml, test/models/group_test.rb, test/system/groups_test.rb
* Creates the group model scaffold
=> Create group model

README.md
* Change production environment link.
=> Change environment production link

app/assets/javascripts/application.js, app/controllers/coordinators_controller.rb, app/controllers/groups_controller.rb, app/controllers/stakeholders_controller.rb, app/controllers/students_controller.rb, app/controllers/supervisors_controller.rb, app/controllers/tutors_controller.rb, app/models/group.rb, app/models/student.rb, app/views/groups/index.html.erb, app/views/groups/new.html.erb, app/views/groups/show.html.erb, app/views/layouts/application.html.erb, app/views/supervisors/index.html.erb, config/routes.rb, db/migrate/20191118043253_create_join_table_groups_students.rb, db/schema.rb
*Create Groups
*Add Students to Groups
*Remove Students from Groups
=> Added groups backend

Gemfile, Gemfile.lock, app/controllers/courses_controller.rb, app/controllers/students_controller.rb, app/controllers/tutors_controller.rb, app/views/courses/export.xlsx.axlsx, app/views/students/export.xlsx.axlsx, app/views/students/index.html.erb, app/views/tutors/export.xlsx.axlsx, app/views/tutors/index.html.erb, config/initializers/mime_types.rb, config/routes.rb
Export Students
Export Courses
Export Tutors
*
=> Added Export to Models as XLSX

app/assets/stylesheets/students.scss, app/controllers/coordinators_controller.rb, app/controllers/stakeholders_controller.rb, app/controllers/students_controller.rb, app/controllers/supervisors_controller.rb, app/controllers/tutors_controller.rb, app/models/student.rb, app/views/coordinators/index.html.erb, app/views/courses/index.html.erb, app/views/groups/index.html.erb, app/views/groups/show.html.erb, app/views/layouts/application.html.erb, app/views/stakeholders/edit.html.erb, app/views/stakeholders/index.html.erb, app/views/stakeholders/new.html.erb, app/views/students/_form.html.erb, app/views/students/index.html.erb, app/views/students/show.html.erb, app/views/supervisors/index.html.erb, app/views/tutors/index.html.erb, app/views/tutors/show.html.erb, db/migrate/20191121211711_add_columns_to_student.rb, db/schema.rb
=> Front end details

db/schema.rb
=> Schema migration

app/controllers/coordinators_controller.rb, app/controllers/stakeholders_controller.rb, app/controllers/supervisors_controller.rb, app/models/coordinator.rb, app/models/course.rb, app/models/stakeholder.rb, app/models/student.rb, app/models/supervisor.rb, app/models/tutor.rb, app/views/coordinators/index.html.erb, app/views/groups/export.xlsx.axlsx, app/views/stakeholders/index.html.erb, app/views/students/export.xlsx.axlsx, app/views/students/index.html.erb, app/views/supervisors/index.html.erb, app/views/tutors/export.xlsx.axlsx, config/routes.rb
IMPORTAR STACKEHOKDERS; COORDINADORES; SUPERVISORES
IGNORAR REPETIDOS AL MOMENTO DE IMPORTAR DE EXCEL
EXPORTACIONES DE TUTORES; STUDENTS;
*
=> Import, Export fixes
